/** Tiny base64 JPEG fixture — same 1×1 grey image the companion mock uses. */
export const FIXTURE_PHOTO_BASE64 =
  '/9j/4AAQSkZJRgABAQEASABIAAD/2wBDAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/2wBDAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/wAARCAABAAEDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAr/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/8QAFAEBAAAAAAAAAAAAAAAAAAAAAP/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/AL/AB//Z';

export function photoForStep(_stepNumber: number): string {
  // Real fixtures land in tests/e2e/fixtures/dac811/step-NN.jpg later; for the
  // happy-path smoke against the mock verifier we send the same canned image.
  return FIXTURE_PHOTO_BASE64;
}
